---
title: Row Details
order: 3
layout: page
---

[[vaadin-grid.row-details]]
= Row Details

[[vaadin-grid.row-details.templates]]
== Defining a Template

In order to use row details, a template must be defined.
The row details template has to be set as a direct child of [vaadinelement]#vaadin-grid# and it must have `class="row-details"`.
The same variables can be used inside the template as in cell templates, namely [propertyname]#index#, [propertyname]#item#, [propertyname]#selected# and [propertyname]#expanded#.

[source,html]
----
<vaadin-grid>
  <template class="row-details">
    These are the details for [[item.value]]!
  </template>
  <vaadin-grid-column>
     ...
  </vaadin-grid-column>
</vaadin-grid>
----

[[vaadin-grid.row-details.expanding-rows]]
== Expanding Rows

After a template has been set, details can be expanded and collapsed in various ways.

API can be used to expand and collapse items using reference to the item object:

[source,javascript]
----
grid.expandItem(item1);
grid.collapseItem(item2);
----

[[vaadin-grid.row-details.accessing]]
== Accessing Expanded Items

After details have been expanded for a row, you can use [propertyname]#expandedItems# to access them.

[source,html]
----
<vaadin-grid expanded-items="{{expandedItems}}">
  <template class="row-details">
    These are the details for [[item.value]]!
  </template>
  <vaadin-grid-column>
     ...
  </vaadin-grid-column>
</vaadin-grid>

<ul>Currently Expanded:
  <template is="dom-repeat" items="[[expandedItems]]">
    <li>[[item.value]</li>
  </template>
</ul>
----

[NOTE]
Similarily to [propertyname]#selectedItems#, [propertyname]#expandedItems# will be cleared when the data source is updated.

[propertyname]#expandedItems# can also be modified to expand or collapse row details. This is especially handy when you want to close all expanded details:

[source,javascript]
----
grid.expandedItems = []; //closes all expanded details.
grid.push('expandedItems', item); //expands row details for 'item'
----

[NOTE]
When modifying [propertyname]#expandedItems#, remember to use the array mutation methods from Polymer.Base

[[vaadin-grid.row-details.activeitem]]
== Expanding and Collapsing Items on activation

You can listen to [propertyname]#active-item-changed# event which is fired whenever a user activates a row in the grid. Then you can access the last activated item by using the `activeItem` of the grid.

[source,html]
----
<vaadin-grid id="grid" active-item-changed="_onActiveItemChanged">
  <template class="row-details">
    These are the details for [[item.value]]!
  </template>
  <vaadin-grid-column>
     ...
  </vaadin-grid-column>
</vaadin-grid>
<script>
  ...
    _onActiveItemChanged: function(e) {
      var item = e.detail.value;

      this.$.grid.expandedItems = item ? [item] : [];
    }
  ...
</script>
----

[[vaadin-grid.row-details.bindings]]
== Expanding and Collapsing Items using Two-Way binding

A variable [propertyname]#expanded# is available inside the row detail template. It is a Boolean variable which can be used two-way to determine if the details are expanded for this item.

[source,html]
----
<vaadin-grid>
  <template class="row-details">
    These are the details for [[item.value]]!
  </template>
  <vaadin-grid-column>
    ...
  </vaadin-grid-column>
  <vaadin-grid-column width="30px">
    <template>
      <paper-checkbox checked="{{expanded}}">Details</paper-checkbox>
    </template>
  </vaadin-grid-column>
</vaadin-grid>
----

[[vaadin-grid.row-details.styling]]
== Styling Row Details

Same way as with other templates, their contents can be fully styled by placing CSS rules in the same scope with [vaadinelement]#vaadin-grid#:

[source,html]
----
<style>
  vaadin-grid .details {
    background-color: red;
  }
</style>
<vaadin-grid>
  <template class="row-details">
    <div class="details">
      These are the details for [[item.value]]!
    </div>
  </template>
  <vaadin-grid-column>
     ...
  </vaadin-grid-column>
</vaadin-grid>
----
