#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Apr 06 17:26:40 EEST 2026
maven-metadata-spring-snapshots.xml.error=
maven-metadata-spring-snapshots.xml.lastUpdated=1772715570707
maven-metadata-vaadin-directory.xml.error=
maven-metadata-vaadin-directory.xml.lastUpdated=1773412606380
maven-metadata-vaadin-prereleases.xml.lastUpdated=1775485600722
