# fly.toml app configuration file generated for vaadin-breadcrumb-cases on 2026-04-17T17:06:30+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vaadin-breadcrumb-cases'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
