rootUrl: http://localhost:8080/components/vaadin-combo-box/test/visual/
gridUrl: http://localhost:4444/wd/hub
screenshotsDir: ./test/visual/screens

system:
  plugins:
    polyserve:
      port: 8080
    sauce: true

browsers:
  chrome:
    desiredCapabilities:
      browserName: "chrome"
      version: "67.0"
      platform: "Windows 10"
