rootUrl: http://localhost:8080/components/vaadin-split-layout/test/visual/
gridUrl: http://localhost:4444/wd/hub
screenshotsDir: ./test/visual/screens

system:
  plugins:
    polyserve:
      port: 8080
    sauce: true

browsers:
  chrome:
    desiredCapabilities:
      browserName: "chrome"
      version: "59.0"
      platform: "Windows 10"

  firefox:
    desiredCapabilities:
      browserName: "firefox"
      version: "47.0"
      platform: "Windows 10"

  # TODO @limonte Doesn't work in Polymer 2, revisit
  # ie:
  #  desiredCapabilities:
  #    browserName: "internet explorer"
  #    version: "11.0"
  #    platform: "Windows 10"

  edge:
    desiredCapabilities:
      browserName: "microsoftedge"
      version: "15"
      platform: "Windows 10"


  # The following setups don't currently work due to selenium driver issues
  # Need to revisit later
  #
  # safari:
  #   desiredCapabilities:
  #     browserName: "safari"
  #     version: "9.0"
  #     platform: "OS X 10.11"
  #
  # iphone:
  #   desiredCapabilities:
  #     browserName: "iphone"
  #     version: "9.2"
  #     platform: "OS X 10.11"
  #
  # android:
  #   desiredCapabilities:
  #     browserName: "android"
  #     version: "5.1"
  #     platform: "Linux"
