---
title: Other features
order: 3
layout: page
---

[[vaadin-date-picker.features]]
= Other Features

== Localization

The [vaadinelement]#vaadin-date-picker# element can be localized through the [propertyname]#i18n# object.

[source,html]
----
<vaadin-date-picker id='my-picker' label="Birthday"></vaadin-date-picker>
----
[source,javascript]
----
document.getElementById('my-picker').i18n = {
  today: 'tänään',
  cancel: 'peruuta',
  firstDayOfWeek: 1,
  monthNames: ['tammikuu','helmikuu','maaliskuu','huhtikuu','toukokuu','kesäkuu',
               'heinäkuu','elokuu','syyskuu','lokakuu','marraskuu','joulukuu'],
  weekdaysShort: ['su','ma','ti','ke','to','pe','la'],
  formatDate: function(d) {
    return [d.getDate(), d.getMonth() + 1, d.getFullYear()].join('.');
  }
}
----

* [propertyname]#i18n.monthNames# – An array of month names starting from January.
* [propertyname]#i18n.weekdaysShort# – An array of short weekday names starting from Sunday.
* [propertyname]#i18n.firstDayOfWeek# – An integer indicating the first day of the week (0 = Sunday, 1 = Monday, etc.).
* [propertyname]#i18n.today# – Translation of the Today shortcut button text.
* [propertyname]#i18n.cancel# – Translation of the Cancel button text.
* [propertyname]#i18n.formatDate# – A function to format given [classname]#Date# object as [classname]#String#.

Once set, the [propertyname]#i18n# property affects how months and dates are displayed in the [vaadinelement]#vaadin-date-picker# dropdown as well as the language of the buttons in the element.


== Initial Position

When [vaadinelement]#vaadin-date-picker# has no selected value and the dropdown is opened, it automatically scrolls to the current month.
You can make it scroll to another month by setting the [propertyname]#initialPosition# property to a date in that month.

When [vaadinelement]#vaadin-date-picker# already has a value selected, opening the dropdown always scrolls to the month with the selected date.

[source,html]
----
<vaadin-date-picker initial-position="2020-05-01"></vaadin-date-picker>
----
