---
title: Other features
order: 3
layout: page
---

[[vaadin-date-picker.features]]
= Other Features

== Localization

The [vaadinelement]#vaadin-date-picker# element can be localized through the [propertyname]#i18n# object.

[source,html]
----
<vaadin-date-picker id="my-picker" label="Birthday"></vaadin-date-picker>
----
[source,javascript]
----
document.getElementById('my-picker').i18n = {
  today: 'tänään',
  cancel: 'peruuta',
  firstDayOfWeek: 1,
  monthNames: ['tammikuu','helmikuu','maaliskuu','huhtikuu','toukokuu','kesäkuu',
               'heinäkuu','elokuu','syyskuu','lokakuu','marraskuu','joulukuu'],
  weekdaysShort: ['su','ma','ti','ke','to','pe','la'],
  formatDate: function(d) {
    return [d.getDate(), d.getMonth() + 1, d.getFullYear()].join('.');
  }
}
----

* [propertyname]#i18n.monthNames# – An array of month names starting from January.
* [propertyname]#i18n.weekdaysShort# – An array of short weekday names starting from Sunday.
* [propertyname]#i18n.firstDayOfWeek# – An integer indicating the first day of the week (0 = Sunday, 1 = Monday, etc.).
* [propertyname]#i18n.today# – Translation of the Today shortcut button text.
* [propertyname]#i18n.cancel# – Translation of the Cancel button text.
* [propertyname]#i18n.formatDate# – A function to format given [classname]#Date# object as [classname]#String#.

Once set, the [propertyname]#i18n# property affects how months and dates are displayed in the [vaadinelement]#vaadin-date-picker# dropdown as well as the language of the buttons in the element.

=== Using Moment.js for Localization

http://momentjs.com/[Moment.js] is a popular JavaScript library for handling date values.
It comes bundled with a set of locale data, which can be utilized to provide most of the localization properties for [vaadinelement]#vaadin-date-picker#.
You can assign the [propertyname]#monthNames#, [propertyname]#weekdaysShort#, [propertyname]#firstDayOfWeek# properties directly from Moment.js.
For the [propertyname]#formatDate# function you can create a simple function that delegates the date value formatting.

See the code example below for details.

[source,html]
----
<!-- Import Moment.js and the locale(s) needed. -->
<script src="bower_components/moment/min/moment.min.js"></script>
<script src="bower_components/moment/locale/fi.js"></script>
----
[source,javascript]
----
// Set the Finnish locale.
moment.locale('fi');

// Assign the i18n property with locale data from Moment.js.
document.querySelector('vaadin-date-picker').i18n = {
  monthNames: moment.months(),
  weekdaysShort: moment.weekdaysShort(),
  firstDayOfWeek: moment.localeData().firstDayOfWeek(),
  today: 'Tänään',
  cancel: 'Peruuta',
  formatDate: function(d) {
    return moment(d).format(moment.localeData().longDateFormat('L'));
  }
};
----

== Initial Position

When [vaadinelement]#vaadin-date-picker# has no selected value and the dropdown is opened, it automatically scrolls to the current month.
You can make it scroll to another month by setting the [propertyname]#initialPosition# property to a date in that month.

When [vaadinelement]#vaadin-date-picker# already has a value selected, opening the dropdown always scrolls to the month with the selected date.

[source,html]
----
<vaadin-date-picker initial-position="2020-05-01"></vaadin-date-picker>
----

== Disabled

When [vaadinelement]#vaadin-date-picker# has a [propertyname]#disabled# property, the input is disabled and the dropdown can't be opened.
You can still set and change the value of the [vaadinelement]#vaadin-date-picker#.

[source,html]
----
<vaadin-date-picker disabled></vaadin-date-picker>
----

== Readonly

When [vaadinelement]#vaadin-date-picker# has a [propertyname]#readonly# property, the dropdown can't be opened.
You can still set and change the value of the [vaadinelement]#vaadin-date-picker#.

[source,html]
----
<vaadin-date-picker readonly></vaadin-date-picker>
----

== Custom Validators

The [vaadinelement]#vaadin-date-picker# implements the [classname]#IronValidatableBehavior#, so it supports custom validators registered with an [elementname]#iron-meta# element.
The validator to be used is defined using the [propertyname]#validator# property.
Notice that it has to be registered with an [elementname]#iron-meta# element to be available.
See the code example below for details.

[source,html]
----
<vaadin-date-picker
  validator="this-year-validator"
  label="Only this year is accepted">
</vaadin-date-picker>

<script>
  new Polymer.IronMeta({
    type: 'validator',
    key: 'this-year-validator',
    value: {
      validate: function(value) {
        var currentYear = new Date().getFullYear();
        return new Date(value).getFullYear() === currentYear;
      }
    }
  });
</script>
----
