export const emails = [
  {
    id: 1,
    from: 'Patricia Nguyen',
    fromEmail: 'p.nguyen@acme.com',
    to: 'David Chen',
    toEmail: 'd.chen@acme.com',
    subject: 'Q1 Budget Review — Meeting Request',
    date: '2026-02-04T09:15:00Z',
    preview: "Hi David, I'd like to schedule a meeting to go over the Q1 budget numbers…",
    body: "<p>Hi David,</p><p>I'd like to schedule a meeting to go over the Q1 budget numbers before the leadership presentation on the 20th. Finance flagged a 12% variance on infrastructure spend that we should discuss.</p><p>Thursday afternoon or Friday morning both seem open on your calendar. Could you confirm which works better?</p>",
  },
  {
    id: 2,
    from: 'Marcus Webb',
    fromEmail: 'm.webb@acme.com',
    to: 'All Engineering',
    toEmail: 'eng-all@acme.com',
    subject: 'New Hire Onboarding Checklist — Please Review',
    date: '2026-02-07T14:30:00Z',
    preview: "Team, we've revamped the onboarding checklist for new engineering hires…",
    body: "<p>Team,</p><p>We've revamped the onboarding checklist for new engineering hires. We have three new developers starting on March 2nd.</p><p>Key changes: a buddy system pairing new hires with senior engineers, and a consolidated setup script for IDE, VPN, repos, and CI/CD permissions.</p><p>The updated checklist is in Confluence under Engineering > Onboarding.</p>",
  },
  {
    id: 3,
    from: 'Aisha Patel',
    fromEmail: 'a.patel@acme.com',
    to: 'Engineering & IT',
    toEmail: 'eng-it@acme.com',
    subject: 'Server Migration — Maintenance Window Feb 21-22',
    date: '2026-02-12T11:00:00Z',
    preview: 'Reminder: the planned server migration to our new data center will take place…',
    body: '<p>Reminder: the server migration takes place February 21–22. The maintenance window opens Saturday at 10 PM EST through Sunday 6 AM EST.</p><p>CI/CD pipelines, staging environments, and the artifact repository will be unavailable. Production systems will not be affected.</p><p>Please ensure any long-running jobs complete before Saturday evening.</p>',
  },
  {
    id: 4,
    from: 'Lena Kowalski',
    fromEmail: 'l.kowalski@acme.com',
    to: 'Product Team',
    toEmail: 'product@acme.com',
    subject: 'Beta Launch Feedback — Summary',
    date: '2026-02-18T16:45:00Z',
    preview: "I've compiled customer feedback from the first two weeks of our beta launch…",
    body: "<p>I've compiled the beta launch feedback highlights.</p><p>Overall sentiment is positive — 78% rated the experience 4 or 5 out of 5. The new dashboard and real-time notifications were called out as major improvements.</p><p>Main complaints: slow exports for large datasets and confusion around the permissions model. Full report attached.</p>",
  },
  {
    id: 5,
    from: 'Thomas Eriksson',
    fromEmail: 't.eriksson@acme.com',
    to: 'David Chen',
    toEmail: 'd.chen@acme.com',
    subject: 'Re: Security Audit Findings — Action Items',
    date: '2026-02-27T08:55:00Z',
    preview: "Following up on last week's security audit. The external team has finalized…",
    body: "<p>Following up on last week's security audit.</p><p>Critical finding: session tokens aren't invalidated properly on password change. Two medium items: overly permissive CORS headers and missing rate limiting on auth endpoints.</p><p>I've created tickets and assigned them to your team. The auditors recommend a 14-day remediation window for the critical item.</p>",
  },
];
