---
title: Objects as Items
order: 4
layout: page
---


[[vaadin-combo-box.item-template]]
= Using Custom Item Template

By default, the items list is displayed in the overlay as a list of plain strings. For some use cases it is not enough, especially when it is required to display a few Object keys in each item.

In order to give a custom markup for items, you can provide a custom item template in the light DOM of [vaadinelement]#vaadin-combo-box#.

[source,html]
----
<vaadin-combo-box
    id="elements-template-box"
    label="Element"
    item-label-path="name"
    item-value-path="symbol">
  <template>
    [[item.number]] <b>[[item.symbol]]</b><br>
    [[item.name]]
  </template>
</vaadin-combo-box>

<script>
  var elementsTemplateBox = document.querySelector('#elements-template-box');

  // elementsJson is an Array of Objects. Item object format:
  //   {name: 'Hydrogen', symbol: 'H', number: 1}
  elementsTemplateBox.items = elementsJson;
</script>
----

In the above example, the [vaadinelement]#vaadin-combo-box# element has the custom item template, that renders [propertyname]#number#, [propertyname]#symbol#, and [propertyname]#name# keys from the given object items.

[[vaadin-combo-box.item-template.custom-element]]

== Styling Items with Custom Item Element

If styling the custom item template contents is necessary, you apply styles by defining a custom item element for your template and item styles.

The following example demonstrates defining a custom element. The [elementname]#my-item# element receives the [propertyname]#item# Object property and displays the specified item keys in columns using flex layout.

[source,html]
.my-item.html
----
<dom-module id="my-item">
  <template>
    <style>
      :host {
        display: flex;
      }

      span {
        flex: 1 0 100px;
        padding: 0 8px;
      }

      #symbol {
        flex: 0 0 2em;
        font-weight: bold;
      }

      #number {
        text-align: right;
      }
    </style>

    <span id="symbol">[[item.symbol]]</span>
    <span>[[item.name]]</span>
    <span id="number">[[item.number]]</span>
  </template>

  <script>
    Polymer({
      is: 'my-item',
      properties: {item: Object}
    });
  </script>
</dom-module>
----

Then you can use the previously defined [elementname]#my-item# element in the item template of [vaadinelement]#vaadin-combo-box#:

[source,html]
----
<link rel="import" href="my-item.html">

<vaadin-combo-box
    id="elements-my-item-box"
    label="Element"
    item-label-path="name"
    item-value-path="symbol">
  <template>
    <my-item item="[[item]]"></my-item>
  </template>
</vaadin-combo-box>

<script>
  var elementsMyItemBox = document.querySelector('#elements-my-item-box');
  elementsMyItemBox.items = elementsJson;
</script>
----
