---
title: Basic Usage
order: 2
layout: page
---


[[vaadin-combo-box.example]]
= Basic Usage

You need to provide the set of items which the user can select with the [propertyname]#items# property.
Current selection is indicated by the [propertyname]#value# and [propertyname]#selectedItem# properties.
You can set or change the selection programmatically by setting the [propertyname]#value# property.
Doing so also updates the visible fields.

When setting the items declaratively, notice that the attribute value needs to be a valid JSON string. You need to use single quotes for the attribute value and double quotes inside the value (in the JSON string). Alternatively, you can escape the double quotes inside the value.

[source,html]
----
<vaadin-combo-box
  label="Element"
  items='["Bohrium", "Boron", "Bromine", "Cadmium", "Caesium", "Calcium"]'
  value="Bromine">
</vaadin-combo-box>
----

Setting the items and value programmatically:

[source,javascript]
----
var combobox = document.querySelector('vaadin-combo-box');
combobox.items = ['Bohrium', 'Boron', 'Bromine', 'Cadmium', 'Caesium', 'Calcium'];
combobox.value = 'Bromine';
----

== Events

The [vaadinelement]#vaadin-combo-box# element dispatches events when the selection changes.
An event contains the [propertyname]#value# property in the [propertyname]#event.detail# object.

Since there are two selection properties, namely [propertyname]#value# and [propertyname]#selectedItem#,
an event is fired for each. [propertyname]#value-changed# event contains the selection as a String value,
whereas [propertyname]#selected-item-changed# contains the selection as an Object.

Note that the order in which these two events are fired might vary depending on the situation.

[source,javascript]
----
var combobox = document.querySelector('vaadin-combo-box');
combobox.addEventListener('value-changed', function(event) {
  console.log(event.detail.value);
});

combobox.addEventListener('selected-item-changed', function(event) {
  console.log(event.detail.value);
});
----

When using the element inside another Polymer element, you can use the declarative binding syntax to subscribe for an event:

[source,html]
----
<dom-module id="my-element">
  <template>
    <vaadin-combo-box on-value-change="valueChanged"></vaadin-combo-box>
  </template>
</dom-module>
<script>
  Polymer({
    is: 'my-element',
    valueChanged: function(event) {
      alert(event.detail.value);
    }
  });
</script>
----

== Forms

The [vaadinelement]#<vaadin-combo-box># element implements the link:https://elements.polymer-project.org/elements/iron-form-element-behavior[[classname]#IronFormElementBehavior#], so it can be used as a field in an link:https://elements.polymer-project.org/elements/iron-form[[elementname]#iron-form#].

[source,html]
----
<form is="iron-form" method="post">
  <vaadin-combo-box name="name" label="Element"></vaadin-combo-box>
  <button>Submit</button>
</form>
<script>
  var form = document.querySelector('form');
  var combobox = document.querySelector('vaadin-combo-box');

  form.addEventListener('iron-form-submit', function() {
    alert('Form submitted with name: ' + form.serialize().name);
    return false;
  });
</script>
----

== Custom Input Values

Users can be allowed also to input their own custom values. By default, this feature is disabled, so it
needs to be explicitly enabled.

[source,html]
----
<vaadin-combo-box allow-custom-value></vaadin-combo-box>
----

When enabled, custom input values are always accepted and used as the value of the [vaadinelement]#vaadin-combo-box#.
If you need to cancel the automatic assignment, you can provide your own listener for the custom-value-set event
that prevents the default behavior.

[source,html]
----
<dom-module id="my-element">
  <template>
    <vaadin-combo-box id="combobox" on-custom-value-set="onCustomValue"></vaadin-combo-box>
  </template>
</dom-module>
<script>
  Polymer({
    is: 'my-element',
    onCustomValue: function(event) {
      // Prevents the custom value to be assigned.
      event.preventDefault();

      this.$.combobox.value = 'Default Value';
    }
  });
</script>
----

== Using Objects as Items

In addition to using Strings as items, Objects can also be used. +
When using Objects, [vaadinelement]#vaadin-combo-box# needs to know which properties are to be used as the display and string values.

By default, [propertyname]#label# and [propertyname]#value# properties are used from the Object as the display value and the [vaadinelement]#vaadin-combo-box# value, respectively.
In the absence of these properties, [propertyname]#toString()# function for the Object is used to translate it into a String.

[source,javascript]
----
var combobox = document.querySelector('vaadin-combo-box');
combobox.items = [{ label: 'Display Value', value: 'Actual Value' }];
----

You can override the default property paths by defining [propertyname]#item-label-path# and [propertyname]#item-value-path# properties.

[source,html]
----
<vaadin-combo-box item-label-path="name.first" item-value-path="name.last"></vaadin-combo-box>
----

[source,javascript]
----
var combobox = document.querySelector('vaadin-combo-box');
combobox.items = [{ name: { first: 'John', last: 'Doe' } }];
----

== Styling

You can customize certain styles of the [vaadinelement]#vaadin-combo-box# with CSS mixins and properties.

[propertyname]#vaadin-combo-box-overlay-max-height# property can be used to override the default maximum height of the overlay.

[source,html]
----
<style is="custom-style">
  #combobox1 {
    --vaadin-combo-box-overlay-max-height: 100%;
  }
</style>
----
