rootUrl: http://localhost:8080/components/vaadin-ordered-layout/test/visual/
gridUrl: http://localhost:4444/wd/hub
screenshotsDir: ./test/visual/screens

system:
  plugins:
    polyserve:
      port: 8080
    sauce: true

browsers:
  firefox:
    desiredCapabilities:
      browserName: "firefox"
      version: "47.0"
      platform: "Windows 10"

  ie:
    desiredCapabilities:
      browserName: "internet explorer"
      version: "11.0"
      platform: "Windows 10"

  android:
    desiredCapabilities:
      browserName: "chrome"
      platform: "Android"
