import '@vaadin/vaadin-lumo-styles/src/props/index.css';
import '@vaadin/vaadin-lumo-styles/src/global/index.css';
import '@vaadin/vaadin-lumo-styles/components/button.css';
import '@vaadin/vaadin-lumo-styles/components/checkbox.css';
import '@vaadin/vaadin-lumo-styles/components/checkbox-group.css';
import '@vaadin/vaadin-lumo-styles/components/custom-field.css';
import '@vaadin/vaadin-lumo-styles/components/date-time-picker.css';
import '@vaadin/vaadin-lumo-styles/components/number-field.css';
import '@vaadin/vaadin-lumo-styles/components/radio-button.css';
import '@vaadin/vaadin-lumo-styles/components/radio-group.css';
import '@vaadin/vaadin-lumo-styles/components/select.css';
import '@vaadin/vaadin-lumo-styles/components/slider.css';
import '@vaadin/vaadin-lumo-styles/components/text-area.css';
import '@vaadin/vaadin-lumo-styles/components/text-field.css';
import '../fixtures/not-animated-styles.css';
import '@vaadin/button';
import '@vaadin/checkbox';
import '@vaadin/checkbox-group';
import '@vaadin/custom-field';
import '@vaadin/date-time-picker';
import '@vaadin/number-field';
import '@vaadin/radio-group';
import '@vaadin/select';
import '@vaadin/slider';
import '@vaadin/text-area';
import '@vaadin/text-field';
import { fieldBaselineSuite } from '../suites/field-baseline.js';

fieldBaselineSuite();
