name: 🤗 Support Question
description: If you have a question 💬, please check out Vaadin Forum!
body:
  - type: markdown
    attributes:
      value: "We primarily use GitHub as an issue tracker. For support questions, please check out https://vaadin.com/forum/. Thank you!"
  - type: input
    id: ignore
    attributes:
      label: Ignore
      description: Ignore
    validations:
      required: true
