#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Apr 17 13:51:12 UTC 2026
maven-metadata-vaadin-directory.xml.error=
maven-metadata-vaadin-directory.xml.lastUpdated=1776145594765
maven-metadata-vaadin-prereleases.xml.lastUpdated=1776433872826
