// This file is generated by scripts/generateMetaPackages.js. Do not edit it by hand.
import '@vaadin/vaadin-core';
import '@vaadin/board';
import '@vaadin/board/vaadin-board-row.js';
import '@vaadin/charts';
import '@vaadin/charts/vaadin-chart-series.js';
import '@vaadin/crud';
import '@vaadin/crud/vaadin-crud-edit-column.js';
import '@vaadin/crud/vaadin-crud-edit.js';
import '@vaadin/dashboard';
import '@vaadin/dashboard/vaadin-dashboard-layout.js';
import '@vaadin/dashboard/vaadin-dashboard-section.js';
import '@vaadin/dashboard/vaadin-dashboard-widget.js';
import '@vaadin/grid-pro';
import '@vaadin/grid-pro/vaadin-grid-pro-edit-column.js';
import '@vaadin/map';
import '@vaadin/rich-text-editor';
