#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Apr 07 12:44:23 EEST 2026
maven-metadata-Vaadin\ Directory.xml.error=
maven-metadata-Vaadin\ Directory.xml.lastUpdated=1765104783941
maven-metadata-vaadin-directory.xml.error=
maven-metadata-vaadin-directory.xml.lastUpdated=1769020341683
maven-metadata-vaadin-prereleases.xml.lastUpdated=1775555063602
maven-metadata-vaadin-snapshots.xml.error=
maven-metadata-vaadin-snapshots.xml.lastUpdated=1765104783941
