window.VaadinOverlaySuites = [
  'vaadin-overlay.html',
  'vaadin-overlay.html?wc-shadydom=true',
  'renderer.html',
  'renderer.html?wc-shadydom=true',
  'focus-trap.html',
  'focus-trap.html?wc-shadydom=true',
  'restore-focus.html',
  'restore-focus.html?wc-shadydom=true',
  'styling.html',
  'styling.html?wc-shadydom=true',
  'templating.html',
  'templating.html?wc-shadydom=true',
  'animations.html',
  'animations.html?wc-shadydom=true',
];
