/**
 * @license
 * Copyright (c) 2021 - 2026 Vaadin Ltd.
 * This program is available under Apache License Version 2.0, available at https://vaadin.com/license/
 */

/**
 * Application-wide default texts for {@link AiFieldMarker}, settable via
 * {@link AiFieldMarker.setDefaults}.
 */
export interface AiFieldMarkerDefaults {
  /**
   * The message shown in the popover explaining the AI fill.
   */
  message?: string;

  /**
   * The label of the revert control.
   */
  revertText?: string;

  /**
   * The accessible label of the badge button and the popover dialog.
   */
  badgeLabel?: string;

  /**
   * The tooltip text of the badge button.
   */
  badgeTooltip?: string;
}

/**
 * Options accepted by {@link AiFieldMarker.mark}.
 */
export interface AiFieldMarkerOptions {
  /**
   * The message shown in the popover explaining the AI fill. Defaults to a
   * built-in English string; override for i18n.
   */
  message?: string;

  /**
   * Optional extra text shown in the popover below the message.
   */
  additionalContent?: string;

  /**
   * The label of the revert control. Defaults to `Revert`.
   */
  revertText?: string;

  /**
   * The accessible label of the badge button and the popover dialog. Defaults
   * to `AI-provided value`.
   */
  badgeLabel?: string;

  /**
   * The tooltip text of the badge button. Defaults to
   * `Field value generated by AI. Click for more details`.
   */
  badgeTooltip?: string;
}

/**
 * Fired from the field element when the user activates the revert control.
 * The host is expected to restore the field's previous value.
 */
export type AiFieldRevertEvent = CustomEvent<{ value: unknown }>;

declare global {
  interface HTMLElementEventMap {
    'ai-field-revert': AiFieldRevertEvent;
  }
}

/**
 * An element that annotates a field as AI-filled. It injects itself into the
 * field's shadow root, draws an "AI" badge anchored to the field, and offers a
 * popover that explains the AI fill and lets the user revert the value.
 *
 * Not intended to be used as a standalone tag; use the static `mark()` /
 * `unmark()` API.
 *
 * Custom popover content can be supplied by slotting an element on the FIELD
 * with `slot="ai-field-marker-popover-content"`; the marker forwards it into the
 * popover. This is the integration point for frameworks (e.g. Flow) that render
 * content as server-side elements in the field's light DOM.
 */
declare class AiFieldMarker extends HTMLElement {
  /**
   * The message shown in the popover explaining the AI fill.
   */
  message: string;

  /**
   * Optional extra text shown in the popover below the message.
   */
  additionalContent: string;

  /**
   * The label of the revert control.
   */
  revertText: string;

  /**
   * The accessible label of the badge button and the popover dialog.
   */
  badgeLabel: string;

  /**
   * The tooltip text of the badge button.
   */
  badgeTooltip: string;

  /**
   * Sets the texts used by every subsequently marked field, so an application
   * can localize them once instead of passing options to each `mark` call.
   * Only the provided keys change; per-call `mark` options still take
   * precedence. Does not retroactively update already-marked fields.
   *
   * @param defaults the default texts to set
   */
  static setDefaults(defaults: AiFieldMarkerDefaults): void;

  /**
   * Marks the given field as AI-filled. Texts default to those set via
   * `setDefaults`; `options` overrides them for this field only.
   *
   * @param field the field to mark
   * @param options optional content overrides
   * @returns the marker instance, or `null` when the field has no shadow root
   */
  static mark(field: HTMLElement, options?: AiFieldMarkerOptions): AiFieldMarker | null;

  /**
   * Removes the AI-filled annotation previously added by `mark`. A no-op when
   * the field is not marked.
   *
   * @param field the field to clear
   */
  static unmark(field: HTMLElement): void;
}

declare global {
  interface HTMLElementTagNameMap {
    'vaadin-ai-field-marker': AiFieldMarker;
  }
}

export { AiFieldMarker };
