#!/usr/bin/env node

/**
 * This script generates the contents of the meta packages, `@vaadin/vaadin-core`
 * and `@vaadin/vaadin`, from the workspace: the `version` and `dependencies` of
 * their `package.json`, and the imports of their entry point.
 *
 * A package is a dependency of `@vaadin/vaadin-core` when it is licensed under
 * Apache-2.0 and of `@vaadin/vaadin` when it is not, which is what separates the
 * core components from the commercial ones. `@vaadin/vaadin` also depends on
 * `@vaadin/vaadin-core`, so that it ships every component.
 *
 * The packages that a meta package depends on but this repository does not
 * build are listed in `EXTERNAL_DEPENDENCIES` and kept from its committed
 * `package.json`, with the version declared there, as they have versions of
 * their own.
 *
 * The entry point imports the root level entry points that the `custom-elements.json`
 * of a package lists and that define a custom element, which leaves out the entry
 * points that only export a mixin or a class. The manifests are generated by
 * `yarn release:cem`, which `yarn release:meta` runs first. The packages that register an
 * iconset rather than a custom element are listed in `ICONSET_PACKAGES`.
 *
 * Run with: yarn release:meta
 * Verify that the committed files are up to date: yarn lint:meta
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import lerna from '../lerna.json' with { type: 'json' };

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const packagesDir = path.join(rootDir, 'packages');

const { version } = lerna;

const META_PACKAGES = [
  { dir: 'vaadin-core', name: '@vaadin/vaadin-core', entryPoint: 'vaadin-core.js', core: true },
  { dir: 'vaadin', name: '@vaadin/vaadin', entryPoint: 'vaadin.js', core: false },
];

// The packages that register an iconset rather than a custom element, which
// their custom elements manifest does not list. Their main entry point is imported.
const ICONSET_PACKAGES = new Set(['icons']);

// The packages that the meta packages depend on but this repository does not
// build. Their version is the one their committed package.json declares, which
// is where to bump them, rather than the version of this repository.
const EXTERNAL_DEPENDENCIES = new Set([
  '@vaadin/router',
  '@vaadin/vaadin-development-mode-detector',
  '@vaadin/vaadin-usage-statistics',
]);

const metaPackageDirs = new Set(META_PACKAGES.map((metaPackage) => metaPackage.dir));

// Sorts names by code unit, the order of a sort with no compare function, which
// keeps the generated files byte for byte the same on every machine
const byName = (a, b) => {
  if (a === b) {
    return 0;
  }
  return a < b ? -1 : 1;
};

/**
 * Reads the `package.json` of a package of the workspace.
 * @param {string} dir - the package directory name, e.g. "button"
 * @returns {object | null} - the parsed `package.json`, or null when there is none
 */
function readPackageJson(dir) {
  const file = path.join(packagesDir, dir, 'package.json');
  return fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf-8')) : null;
}

/**
 * Lists the packages of the workspace that the meta packages ship, in two
 * groups: the ones licensed under Apache-2.0 and the commercial ones.
 * @returns {{ core: object[], commercial: object[] }}
 */
function collectPackages() {
  const core = [];
  const commercial = [];

  for (const dir of fs.readdirSync(packagesDir).sort(byName)) {
    if (metaPackageDirs.has(dir)) {
      continue;
    }

    const packageJson = readPackageJson(dir);
    if (!packageJson || packageJson.private) {
      continue;
    }

    const group = packageJson.license === 'Apache-2.0' ? core : commercial;
    group.push({ dir, ...packageJson });
  }

  return { core, commercial };
}

/**
 * Lists the modules of a package that the entry point of a meta package imports.
 * The main entry point comes first and is imported by package name, the other
 * ones by their path.
 * @param {object} packageJson - the `package.json` of the package
 * @returns {string[]} - e.g. ["@vaadin/login", "@vaadin/login/vaadin-login-form.js"]
 */
function collectImports(packageJson) {
  if (ICONSET_PACKAGES.has(packageJson.dir)) {
    return [packageJson.name];
  }

  // The packages that define no custom element, e.g. the theme ones, have no manifest
  const manifest = path.join(packagesDir, packageJson.dir, 'custom-elements.json');
  if (!fs.existsSync(manifest)) {
    return [];
  }

  // The root level modules are the entry points, each re-exporting its module in `src`.
  // An entry point that only exports a mixin or a class, e.g. `vaadin-item-mixin.js`,
  // defines no custom element and thus does not belong to the entry point of a meta package.
  const { modules } = JSON.parse(fs.readFileSync(manifest, 'utf-8'));
  const definesElement = ({ declaration }) =>
    modules.some((module) => module.path === declaration.module && module.declarations.some((d) => d.customElement));

  const entryPoints = modules
    .filter((module) => !module.path.includes('/') && module.exports.some(definesElement))
    .map((module) => module.path)
    .sort(byName);

  // The main entry point of the package comes first, imported by package name
  const main = entryPoints.indexOf(packageJson.main);
  if (main > 0) {
    entryPoints.unshift(entryPoints.splice(main, 1)[0]);
  }

  return entryPoints.map((file) => (file === packageJson.main ? packageJson.name : `${packageJson.name}/${file}`));
}

/**
 * Creates the contents of the entry point of a meta package.
 * @param {string[]} imports - the modules to import
 * @returns {string}
 */
function createEntryPoint(imports) {
  return [
    '// This file is generated by scripts/generateMetaPackages.js. Do not edit it by hand.',
    ...imports.map((module) => `import '${module}';`),
    '',
  ].join('\n');
}

/**
 * Creates the contents of the `package.json` of a meta package, keeping every
 * field of the committed one but the generated `version` and `dependencies`.
 * The packages of the workspace are pinned to the version of the repository,
 * the external ones keep the version the committed `package.json` declares.
 * @param {object} packageJson - the committed `package.json`
 * @param {string[]} dependencies - the names of the packages of the workspace to depend on
 * @returns {string}
 */
function createPackageJson(packageJson, dependencies) {
  const external = Object.entries(packageJson.dependencies ?? {}).filter(([name]) => EXTERNAL_DEPENDENCIES.has(name));
  const pinned = dependencies.map((name) => [name, version]);

  const generated = {
    ...packageJson,
    version,
    dependencies: Object.fromEntries([...external, ...pinned].sort(([a], [b]) => byName(a, b))),
  };

  return `${JSON.stringify(generated, null, 2)}\n`;
}

const check = process.argv.includes('--check');

if (!fs.existsSync(path.join(rootDir, 'custom-elements.json'))) {
  console.error(
    'The custom elements manifests are missing. Run `yarn release:meta` or `yarn lint:meta`, which generate them first.',
  );
  process.exit(1);
}

const { core, commercial } = collectPackages();
const outdated = [];

for (const metaPackage of META_PACKAGES) {
  const packageJson = readPackageJson(metaPackage.dir);
  if (!packageJson) {
    throw new Error(`No package.json found for ${metaPackage.name}`);
  }

  const packages = metaPackage.core ? core : commercial;
  const dependencies = packages.map((pkg) => pkg.name);
  const imports = packages.flatMap((pkg) => collectImports(pkg));

  if (!metaPackage.core) {
    dependencies.unshift('@vaadin/vaadin-core');
    imports.unshift('@vaadin/vaadin-core');
  }

  const files = {
    'package.json': createPackageJson(packageJson, dependencies),
    [metaPackage.entryPoint]: createEntryPoint(imports),
  };

  for (const [name, content] of Object.entries(files)) {
    const file = path.join(packagesDir, metaPackage.dir, name);

    if (check) {
      if (!fs.existsSync(file) || fs.readFileSync(file, 'utf-8') !== content) {
        outdated.push(path.relative(rootDir, file));
      }
    } else {
      fs.writeFileSync(file, content);
      console.log(`Generated ${path.relative(rootDir, file)}`);
    }
  }

  if (!check) {
    console.log(`${metaPackage.name}: ${dependencies.length} packages, ${imports.length} imports`);
  }
}

if (outdated.length > 0) {
  console.error(
    [
      `The meta packages are out of date: ${outdated.join(', ')}`,
      'Run `yarn release:meta` and commit the result.',
    ].join('\n'),
  );
  process.exit(1);
}
