import '../theme/lumo/vaadin-date-picker-styles.js';
import '../theme/lumo/vaadin-date-picker-overlay-styles.js';
import '../theme/lumo/vaadin-date-picker-overlay-content-styles.js';
import '../theme/lumo/vaadin-month-calendar-styles.js';
import '../theme/lumo/vaadin-date-picker-styles.js';
import '@vaadin/input-container/theme/lumo/vaadin-input-container-styles.js';
import './not-animated-styles.js';
import '../src/vaadin-lit-date-picker.js';
import './value-commit.common.js';
