name: Material

on: pull_request

jobs:
  tests:
    name: Visual tests
    runs-on: ubuntu-latest
    if: github.repository_owner == 'vaadin'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Setup Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn --frozen-lockfile --no-progress --non-interactive

      - name: Visual tests
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: yarn test:material

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: screenshots
          path: |
            packages/*/test/visual/material/screenshots/*/failed/*.png
            packages/vaadin-material-styles/test/visual/screenshots/failed/*.png
