name: Unit tests

on: pull_request

permissions:
  contents: read

env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

jobs:
  chrome:
    name: Chrome
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.0-noble
      options: --ipc=host

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn --frozen-lockfile --no-progress --non-interactive

      - name: Test
        run: yarn test
  firefox:
    name: Firefox
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.0-noble
      options: --ipc=host

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn --frozen-lockfile --no-progress --non-interactive

      - name: Test
        run: yarn test:firefox
  webkit:
    name: WebKit
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.0-noble
      options: --ipc=host

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn --frozen-lockfile --no-progress --non-interactive

      - name: Test
        run: yarn test:webkit
