name: Visual tests

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [main]

permissions:
  contents: read

env:
  _HEAD_SHA: ${{ github.event.pull_request.head.sha }}
  VISUAL_TESTS_DOCKER_IMAGE: mcr.microsoft.com/playwright:v1.56.0-jammy
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

jobs:
  base:
    environment: ${{ github.event.pull_request.head.repo.fork && 'PR-validation' || '' }}
    name: Base
    runs-on: ubuntu-latest
    if: github.repository_owner == 'vaadin'
    container:
      image: ${{ env.VISUAL_TESTS_DOCKER_IMAGE }}
      options: --ipc=host

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'
          ref: ${{ env._HEAD_SHA }}

      - name: Enable Corepack
        run: corepack enable

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn --frozen-lockfile --no-progress --non-interactive

      - name: Visual tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 20
          retry_wait_seconds: 60
          max_attempts: 3
          command: yarn test:playwright:base

      - uses: actions/upload-artifact@v6
        if: ${{ failure() }}
        with:
          name: base-screenshots
          path: |
            packages/*/test/visual/base/screenshots/*/failed/*.png

  lumo:
    environment: ${{ github.event.pull_request.head.repo.fork && 'PR-validation' || '' }}
    name: Lumo
    runs-on: ubuntu-latest
    if: github.repository_owner == 'vaadin'
    container:
      image: ${{ env.VISUAL_TESTS_DOCKER_IMAGE }}
      options: --ipc=host

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'
          ref: ${{ env._HEAD_SHA }}

      - name: Enable Corepack
        run: corepack enable

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn --frozen-lockfile --no-progress --non-interactive

      - name: Visual tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 20
          retry_wait_seconds: 60
          max_attempts: 3
          command: yarn test:playwright:lumo

      - uses: actions/upload-artifact@v6
        if: ${{ failure() }}
        with:
          name: lumo-screenshots
          path: |
            packages/*/test/visual/lumo/screenshots/*/failed/*.png
            packages/vaadin-lumo-styles/test/visual/screenshots/failed/*.png

  aura:
    environment: ${{ github.event.pull_request.head.repo.fork && 'PR-validation' || '' }}
    name: Aura
    runs-on: ubuntu-latest
    if: github.repository_owner == 'vaadin'
    container:
      image: ${{ env.VISUAL_TESTS_DOCKER_IMAGE }}
      options: --ipc=host

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'
          ref: ${{ env._HEAD_SHA }}

      - name: Enable Corepack
        run: corepack enable

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn --frozen-lockfile --no-progress --non-interactive

      - name: Visual tests (default)
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 20
          retry_wait_seconds: 60
          max_attempts: 3
          command: yarn test:playwright:aura

      - name: Visual tests (dark)
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 20
          retry_wait_seconds: 60
          max_attempts: 3
          command: yarn test:playwright:aura:dark

      - uses: actions/upload-artifact@v6
        if: ${{ failure() }}
        with:
          name: aura-screenshots
          path: |
            packages/*/test/visual/aura/screenshots/dark/*/failed/*.png
            packages/*/test/visual/aura/screenshots/default/*/failed/*.png
