////
---
title: Overview
order: 0
layout: page
---
////

= Vaadin Upload Overview

The `vaadin-upload` is a Polymer element for uploading multiple files to server.

It allows users to add their files by dropping them directly into the component. Also it has the “Add files” button, which opens the native browser file dialog for selecting the file or files to process.

All files added by user are displayed in a file list inside the element.

The added files would be automatically uploaded to server. The uploading of multiple files is performed simultaneously. The list indicates the state and uploading progress for each file.

Each file could be removed from the list by user by pressing the corresponding “×” icon. In this case, if the file uploading has been in progress, then the upload process would be aborted.

== Example Usage

[source,html]
<vaadin-upload>
</vaadin-upload>

== Events

`vaadin-upload` dispatches events when files are added or removed as well as for every upload state change of each file.

=== Supported Events

The following events are currently supported:

file-add:: Fired when file is added by user, either by dropping them into the component or by using the “Add Files” button.

=== Event Details and Listening

Each event contains the `File` object in `event.detail.file` property. The upload events also have `event.detail.xhr` property with corresponding `XMLHttpRequest` instance.

In order to listen for an event, use a regular `addEventListener` method:

[source,javascript]
----
function fileAdded(event) {
  alert(event.detail.file.name + ' was added');
}

var upload = document.querySelector('vaadin-upload');
upload.addEventListener('file-add', fileAdded);
----

Also, when using inside another Polymer element, you can use declarative binding syntax to subscribe for an event with a hosting element method:

[source,html]
----
<dom-module id="my-element">
  <template>
    <vaadin-upload on-file-add="fileAdded"></vaadin-upload>
  </template>
</dom-module>
<script>
  Polymer({
    is: 'my-element',
    fileAdded: function(event) {
      alert(event.detail.file.name + ' was added');
    }
  });
</script>
----
