---
title: Basic Usage
order: 2
layout: page
---


[[vaadin-upload.example]]
= Basic Usage

The user can select one or more files opening the browser file selector or dropping files from the desktop to the component.

The developer can customize validations using element attributes, or programmatically using the JavaScript API.

[source,html]
----
<vaadin-upload target="http://foo.bar/upload"></vaadin-upload>
----

== Events

The `vaadin-upload` dispatches events when files are added, removed, rejected, as well as for every upload state change per file.
You can use those events for either changing the behavior of the process, or preventing default actions.
For a full list of events and descriptions, please read the API documentation.

=== Event Details
All events contains the [classname]#File# object in the `event.detail.file` property.
Additionally upload events also have `event.detail.xhr` property with corresponding [classname]#XMLHttpRequest# instance.

In this example we listen to `file-add` events, fired whenever the user adds a new file to the queue:

[source,javascript]
----
var upload = document.querySelector('vaadin-upload');
upload.addEventListener('file-add', function(e) {
  alert(event.detail.file.name + ' was added');
});
----

Also, when using the element inside another `Polymer` element, you can use the declarative binding syntax to subscribe for an event:

[source,html]
----
<dom-module id="my-element">
  <template>
    <vaadin-upload on-file-add="fileAdded"></vaadin-upload>
  </template>
</dom-module>
<script>
  Polymer({
    is: 'my-element',
    fileAdded: function(event) {
      alert(event.detail.file.name + ' was added');
    }
  });
</script>
----
